### ISSUE TITLE
Trojan at zip file?

### ISSUE THREAD

**Issue by leandroribeiro** [schombert/Project-Alice#1129]
Hey man,

I dont know if this is a false positive, but Windows Defender "detect" a Trojan at the zip file (1.0.9.7z) in the last release file. 

Trojan:Win32/Znyonm

**Comment by chriskalos** [comment]
@schombert There should be more investigation here. You cannot just say that it's a false positive and move on - that looks very suspicious on your part. How is it that the VirusTotal result for the latest version has 14 hits as malware? We cannot possibly know what the .exe files shipped in the Releases tab contain... There must be a reason 14 antivirus software are sounding alarms over these files.

**Comment by schombert** [comment]
See attached image. I have verified that it is a false positive. 
![report](https://github.com/schombert/Project-Alice/assets/22087402/dd9be466-2453-40af-ac59-55a766e6f0a5)
