### ISSUE TITLE
Crash right after "Start game"

### ISSUE THREAD

**Issue by McSimKammerer** [schombert/Project-Alice#1153]
Win11
AMD Ryzen 5 7600X
NVidia, driver v.528.24
Vic2 fresh install (steam)
Alice v.1.0.10, files copied to `\steamapps\common\Victoria 2\`:
```
assets/
Alice.exe
Alice512.exe
AliceSSE.exe
dbg_alice.exe
launch_alice.exe
```
`launch_alice.exe` running successfully
`Start game` - immediate crash 
[crash.dmp](https://github.com/schombert/Project-Alice/files/14515632/crash.dmp)

**Comment by schombert** [comment]
noted, but I suggest also consulting the tech support channel in the discord to see if you can find anyone else with the same problem and/or a solution.

**Comment by McSimKammerer** [comment]
Nobody is answering in discord.
Is there any chance to get help at all?

**Comment by Nivaturimika** [comment]
what cpu do you have
