### ISSUE TITLE
[Solved] How to run Project Alice on Ubuntu/PopOS without building a Linux distribution

### ISSUE THREAD

**Issue by jan-gebauer** [schombert/Project-Alice#1183]
Hi,

I managed to get Project Alice to run on PopOS. I did it by using Lutris and [this guide](https://forums.lutris.net/t/very-brief-tutorial-on-manually-installing-a-game-in-lutris/2028). The setup is the same as for Windows, the new thing is how you run it using Lutris. For the Wine version, I used the one that was already pre-installed, so I didn't fiddle with that.

I also managed to load up the mod Divergences of Darkness. I have not yet tried Multiplayer but I will at some point.

I'd be very happy to make this into a formal commit, if there is an interest. I just wanted to get something out the door before I forget to share.

**Comment by Nivaturimika** [comment]
We do have a native Linux build - it's just missing the launcher, unfortunely.
We would appreciate you documenting your lutris process in detail

**Comment by jan-gebauer** [comment]
I wrote up something here #1199 

I tried to do the build but it was all very confusing.
