### ISSUE TITLE
Miscalculation in Budget

### ISSUE THREAD

**Issue by garvey96** [schombert/Project-Alice#1261]
![image](https://github.com/schombert/Project-Alice/assets/83272743/6ac2186c-0a15-4080-8398-d453d26d0029)

The expenses stated are much too high. projected daily balance doesn't match the balance shown in the preview.
Is also possible that these are real expenses are are not able to be fulfilled.

**Comment by schombert** [comment]
Since you do not have debt spending enabled (the checkbox next to the piechart on the left) your actual spending will be reduced to fit inside your budget. The budget window shows your target spending, not your effective net spending.
