### ISSUE TITLE
Goods price is not limited

### ISSUE THREAD

**Issue by EmpathieB** [schombert/Project-Alice#1766]
Hello,

The price of goods is not limited contrary to base game.
On the wiki it is specified that prices should be :
- max price => base price * 5
- min price => base price * 0.22

I have read the project docs and it says the following :
`Prices are then limited to being within 1/5th to 5x the base price of the commodity.`

It seems there is a bug somewhere preventing the limits to work.

Both higher limits :
![liquor price](https://github.com/user-attachments/assets/84bce5ed-6361-4e24-a89e-b3ed5d5dd4de)

And lower limits :
![tropicalwood](https://github.com/user-attachments/assets/46432a89-bc0b-450d-9169-bcd2bc9b1162)

And while quickly checking the code, I can see no reference to these limits :
https://github.com/schombert/Project-Alice/blob/main/src/economy/economy.cpp#L3896
```C++
		float speed_modifer = (overdemand_factor - oversupply_factor);

		float price_speed = 0.05f * speed_modifer;

		if(current_price < 1.f) {
			price_speed *= current_price;
		} else {
			price_speed *= math::sqrt(current_price);
		}

		current_price += price_speed;

		state.world.commodity_set_current_price(cid, std::clamp(current_price, 0.001f, 100000.0f));
```

**Comment by schombert** [comment]
Yes, these limits were removed as part of the work to make the economy more generally functional. Hitting the limit would make supply and demand "wacky" at those extremes, and the limits being so small in range made that behavior quite common
