### ISSUE TITLE
trying to compile the code but failed

### ISSUE THREAD

**Issue by js00070** [schombert/Project-Alice#714]
> C:\Users\violi\code\Project-Alice\out\build\x64-debug-windows\_deps\catch2-src\single_include\catch2\catch.hpp(2327): error C2220: the following warning is treated as an error
C:\Users\violi\code\Project-Alice\out\build\x64-debug-windows\_deps\catch2-src\single_include\catch2\catch.hpp(2327): warning C4388: '!=': signed/unsigned mismatch
  C:\Users\violi\code\Project-Alice\out\build\x64-debug-windows\_deps\catch2-src\single_include\catch2/catch.hpp(2327): note: the template instantiation context (the oldest one first) is
  C:\Users\violi\code\Project-Alice\tests\scenario_building.cpp(304): note: see reference to function template instantiation 'const Catch::BinaryExpr<LhsT,const int &> Catch::ExprLhs<LhsT>::operator !=<int>(const RhsT &)' being compiled
          with
          [
              LhsT=const unsigned __int64 &,
              RhsT=int
          ]
  C:\Users\violi\code\Project-Alice\tests\scenario_building.cpp(304): note: see the first reference to 'Catch::ExprLhs<const unsigned __int64 &>::operator !=' in 'C_A_T_C_H_T_E_S_T_55'

I added `set(CMAKE_COMPILE_WARNING_AS_ERROR OFF)` into `tests/CMakeLists.txt` but it didn't work. How can I disable the warning as error feature for a dependency library?

**Comment by schombert** [comment]
It's ok if the tests don't build; they often get out of date. Or just cast the value in question to an unsigned int; that's probably easier than changing things in CMake.

**Comment by js00070** [comment]
> It's ok if the tests don't build; they often get out of date. Or just cast the value in question to an unsigned int; that's probably easier than changing things in CMake.

Thanks:) I can successfully compile the code after casting the value. 

I'm interested in this project and I'm happy to do some contribution. I'm trying to get familiar with the code. Do you think it would be suitable for me to update the tests code if needed?

**Comment by schombert** [comment]
Sure, if you want to. The tests were mainly designed for the loading and parsing code, and we haven't made changes to that in a while, so they don't get much use (one day we should add more tests ...). You can also feel free to use the discord to ask any questions you have. Here, I am the only person who can help you out, while on discord there are other contributors in different time zones who may be able to answer questions when I am not available.
