### ISSUE TITLE
Is playing on Linux (Ubuntu/Pop!_OS) possible?

### ISSUE THREAD

**Issue by jan-polivka** [schombert/Project-Alice#790]
Hi

Is playing on Linux (Ubuntu/Pop!_OS) possible? I see that there is only a pre-compiled package for Windows but I saw in the documentation that it is possible to compile on a Debian-based distro. I just want to check the state of the app before I go off to fight CMake.

Thanks!

**Comment by schombert** [comment]
People have had success running it on linux, yes. However, none of the active devs are using linux currently, so I can't guarantee that things are currently working as intended. And there is no launcher on linux, so you will either have to play vanilla or write a tool to generate scenario files.

**Comment by OptimizedForDensity** [comment]
I run it on Linux and I can confirm it works. You have to run the `Alice` executable from the command line and with a few changes to `entry_point_nix.cpp` you can even get it to compile mods. I can explain what lines you need to change if you want me to.

**Comment by kenny-patrick** [comment]
> I run it on Linux and I can confirm it works. You have to run the `Alice` executable from the command line and with a few changes to `entry_point_nix.cpp` you can even get it to compile mods. I can explain what lines you need to change if you want me to.

Can you elaborate? I'm currently trying to get this running on Linux with GFM
