### ISSUE TITLE
AI problem

### ISSUE THREAD

**Issue by SoyPobre123** [schombert/Project-Alice#889]
I dont know why but, when i play for example, prussia and a little bit later, randomly France Declares war on me Cuz of rhineland, i played as ottoman Empire and then austria and egypt declared war on me in 1836-1837 and the Armies are just ridiculous. but the other parts of the mod Still Amazing, good job so Far. but fix that please and add some event pause option, like Hoi4 and vanilla Vic2 and HOW THE FRENCH ARMY OF 90K GUYS ARE DEFEATING AN 123K-130K PRUSSIAN GUYS

**Comment by wxwisiasdf** [comment]
difficulty settings will be added l8tr

**Comment by wxwisiasdf** [comment]
event pausing is available on message settings btw

**Comment by SoyPobre123** [comment]
oh Really? damn maybe im kinda blind, anyways, so all the fault was the Difficulty? sooo uh um i dont wanna be rude dude i was going to say something kinda rude about that.
