### ISSUE TITLE
Assimilation Rework

### ISSUE THREAD

**Issue by ProudAssyrian** [schombert/Project-Alice#973]
Pops assimilate and retain their religion
Religions spread organically (although the ones with pagan modifiers will not)
They may proselytize within their ingroup and animists being first priority
(This will not always be as such)
Religions (Greek Orthodox and Coptic Pope of Alexandria) get money from their believers, which then is done to proselytize (amongst pagans)
The same religion can have different bishops (could be in conflict)
Assimilation can be done to minority cultures, and is done based on who the Capitalists are
If the Capitalists in the province are not accepted, then assimilation will be done towards them
Melting pots can be created, but not of different races (it's rare to see race-mixing, and most race-mixing that did occur happened before 1836, such as between the American Indians and the Spanish, and it's not too much any further)
Immigration does not discard culture, but creates diaspora cultures
Certain diaspora communities will not assimilate (if they are of different religions, so that there is no assimilation of Armenians in Russia, but there continues to be a diaspora)
Diasporas may repatriate
Genocides occur via expulsions
Conversions of certain religions will not occur
Pop growth is uneven, based on pop income and literacy (higher income is more pops because of higher SOL, and lower literacy is more pops)

**Comment by schombert** [comment]
you may want to take your ideas to the feature requests section of the discord
